apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: proxypool
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxypool
  namespace: proxypool
spec:
  storageClassName: azure-file
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: proxypool
      name: proxypool
      namespace: proxypool
    spec:
      ports:
        - name: "5555"
          port: 5555
          targetPort: 5555
      selector:
        io.kompose.service: proxypool
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: proxypool
      name: proxypool
      namespace: proxypool
    spec:
      replicas: 2
      revisionHistoryLimit: 1
      strategy: {}
      selector:
        matchLabels:
          io.kompose.service: proxypool
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose.yml -o deployment.yml
            kompose.version: 1.20.0 ()
          creationTimestamp: null
          labels:
            io.kompose.service: proxypool
        spec:
          containers:
            - env:
                - name: REDIS_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: connection_string
                - name: REDIS_PORT
                  value: '6379'
              image: germey/proxypool:${TAG}
              name: proxypool
              resources:
                limits:
                  memory: "500Mi"
                  cpu: "300m"
                requests:
                  memory: "500Mi"
                  cpu: "300m"
              ports:
                - containerPort: 5555
              volumeMounts:
                - mountPath: "/app/proxypool/crawlers/private"
                  name: proxypool
          restartPolicy: Always
          volumes:
            - name: proxypool
              persistentVolumeClaim:
                claimName: pvc-proxypool
    status: {}
kind: List
metadata: {}
